# Generated by Django 2.2.1 on 2019-06-20 09:06

from django.db import migrations, models
import search.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_year', search.models.YearMonthField(max_length=20)),
                ('registered_day', models.DateTimeField(verbose_name='Registered Date')),
                ('brand', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=20)),
                ('fuel', models.CharField(choices=[('LPG', 'lpg'), ('GAS', 'gasoline'), ('DIESEL', 'diesel'), ('HYBRID', 'HYBRID'), ('ELEC', 'electric'), ('BI', 'bi_fuel')], default='GAS', max_length=6)),
                ('gear', models.CharField(choices=[('AUTO', 'auto'), ('MAN', 'manual')], default='AUTO', max_length=4)),
                ('kms', models.IntegerField(null=True)),
                ('region', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('pend', 'pending'), ('auction', 'in_auction'), ('done', 'done_auction')], default='pend', max_length=7)),
                ('photo', models.ImageField(null=True, upload_to='')),
            ],
        ),
    ]
