# Generated by Django 2.2.1 on 2019-06-24 01:09

from django.db import migrations, models
import django.db.models.deletion
import search.models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Make',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.Make')),
            ],
        ),
        migrations.RemoveField(
            model_name='car',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='car',
            name='model',
        ),
        migrations.RemoveField(
            model_name='car',
            name='model_year',
        ),
        migrations.RemoveField(
            model_name='car',
            name='type',
        ),
        migrations.AlterField(
            model_name='car',
            name='registered_day',
            field=models.DateField(verbose_name='Registered Date'),
        ),
        migrations.CreateModel(
            name='SubModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('model_year', search.models.YearMonthField(max_length=20)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.Model')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='sub_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='search.SubModel'),
        ),
    ]
