# Generated by Django 2.2.1 on 2019-06-22 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_auto_20190623_0224'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='sub_model_name',
            new_name='sub_model',
        ),
        migrations.RemoveField(
            model_name='car',
            name='make',
        ),
        migrations.RemoveField(
            model_name='car',
            name='model',
        ),
    ]
